SELECT*from customer limit 20;

-- . What is the Total Revenue?
SELECT SUM(purchase_amount) AS total_revenue
FROM customer;

-- How Many Customers Are There?
SELECT COUNT(*) AS total_customers
FROM customer;

--  What is the total revenue generated by male vs. female customers?
SELECT gender,SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;

-- Which customers used a discount but still spent more than the average purchase amount? 
-- SELECT AVG(purchase_amount) FROM customer;
select customer_id, purchase_amount 
from customer 
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer);

--  Which categories generate high revenue but have low customer ratings?
SELECT category,
       SUM(purchase_amount) AS revenue,
       ROUND(AVG(review_rating),2) AS avg_rating
FROM customer
GROUP BY category
HAVING avg_rating < 3.5
ORDER BY revenue DESC;
-- 
-- Are subscription customers more valuable than non-subscribers? 
SELECT subscription_status,
       COUNT(*) AS customers,
       AVG(purchase_amount) AS avg_purchase,
       SUM(purchase_amount) AS revenue
FROM customer
GROUP BY subscription_status;

-- Which locations have many customers but low revenue?
SELECT location,
       COUNT(*) AS customers,
       SUM(purchase_amount) AS revenue
FROM customer
GROUP BY location
ORDER BY customers DESC; 

-- Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, purchase_amount 
from customer 
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer);

-- Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

 -- Which products are purchased frequently but generate low revenue?
 SELECT item_purchased,
       COUNT(*) AS orders,
       SUM(purchase_amount) AS revenue
FROM customer
GROUP BY item_purchased
ORDER BY orders DESC;

 --  Compare the average Purchase Amounts between Standard and Express Shipping.
 select shipping_type , 
 ROUND(AVG(purchase_amount),2) as avg_amount
 from customer
 WHERE shipping_type in ('Standard', 'Express')
 GROUP BY shipping_type;

--  Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC;

-- Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


-- Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;

-- What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;

-- Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

--  What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;